name: Step 0, Welcome

# This step triggers after the learner creates a new repository from the template.
# This workflow updates from step 0 to step 1.

on:
  # Trigger when a push happens to main (which occurs after repo creation from a template)
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  get_current_step:
    name: Check current step number
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - id: get_step
        run: |
          echo "current_step=$(cat .github/steps/-step.txt)" >> $GITHUB_OUTPUT
    outputs:
      current_step: ${{ steps.get_step.outputs.current_step }}

  on_start:
    name: Proceed to Step 1
    needs: get_current_step
    if: >-
      ${{ !github.event.repository.is_template
          && needs.get_current_step.outputs.current_step == 0 }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Prepare branch and update README
        run: |
          echo "Ensure we are on step 0"
          if [ "$(cat .github/steps/-step.txt)" != 0 ]
          then
            echo "Not on step 0 — exiting."
            exit 0
          fi

          echo "Create a new branch"
          BRANCH=update-step-1
          git checkout -b $BRANCH

          echo "Trigger step 1 README"
          sed -i.bak 's/Step 0/Step 1/' README.md || true

          echo "Make commit"
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
          git add README.md
          git commit -m "Progress to Step 1"

          echo "Push branch"
          git push --set-upstream origin $BRANCH

          echo "Return to main"
          git checkout main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update to step 1
        uses: skills/action-update-step@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          from_step: 0
          to_step: 1
          branch_name: update-step-1

