name: Step X - Finish

# This step is the final one and does not require any user-triggered events.
# It completes the course and renders the Finish README.

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  get_current_step:
    name: Check current step number
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - id: get_step
        run: echo "current_step=$(cat .github/steps/-step.txt)" >> $GITHUB_OUTPUT
    outputs:
      current_step: ${{ steps.get_step.outputs.current_step }}

  finish_course:
    name: Display Finish Step
    needs: get_current_step
    if: ${{ needs.get_current_step.outputs.current_step == 'X' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Log completion message
        run: echo "🎉 Course complete! Showing finish README."
